---
name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1

      - name: Install python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          python-version-file: 'pyproject.toml'

      - name: make sure poetry lockfile is up to date
        run: poetry check --lock && echo Lockfile is ok, $(poetry --version)
        shell: bash

      - name: install deps
        if: steps.setup-python.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Run the linters
        run: poetry run make lint

  build-image:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image identifier
        id: image
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Log in to the container registry
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.image.outputs.lowercase }}:latest
            ghcr.io/${{ steps.image.outputs.lowercase }}:${{ github.sha }}

          build-args: |
            PYTHON_VERSION=${{ steps.setup-python.outputs.python-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
